DROP TABLE IF EXISTS al;
CREATE TABLE IF NOT EXISTS al (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IP TEXT NOT NULL,
    URL TEXT NOT NULL,
    USERNAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    FIRST_TIME TEXT NOT NULL,
    DATA_RECEIVED TEXT NOT NULL,
    DONE TEXT NOT NULL,
    DATA TEXT NOT NULL,
    EMPTY TEXT NOT NULL,
    RECEIVED TEXT NOT NULL,
    SCode TEXT NOT NULL,
    action_list TEXT NOT NULL,
    IMAGE BLOB
);
