DROP TABLE IF EXISTS al;
CREATE TABLE IF NOT EXISTS al (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SCode TEXT NOT NULL,
    action_list TEXT NOT NULL
);